name: Release Scilab AppImages
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 11 * * 0-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      scilab_version: ${{ steps.set_version.outputs.scilab_version }}
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: bash build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: Scilab.AppImage
          path: "."

      - id: set_version
        run: echo "scilab_version=$SCILAB_VERSION" >> $GITHUB_OUTPUT

  release:
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: Scilab.AppImage

      # Snapshot Release
      - name: get date
        run: |
          SNAPSHOT_TAG="$(date --utc +'%Y%m%d-%H%M%S')"
          echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"
        continue-on-error: false
      - name: create snapshot
        uses: softprops/action-gh-release@v2
        with:
          name: "Snapshot ${{ needs.build.outputs.scilab_version }}"
          tag_name: "${{ needs.build.outputs.scilab_version }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: false
          files: |
            *.AppImage*
        continue-on-error: false

      # Continuous releases
      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Continuous builds
          automatic_release_tag: continuous
          prerelease: false
          draft: false
          files: |
            *.AppImage*
          repo_token: ${{ secrets.GITHUB_TOKEN }}
